### ISSUE TITLE
爬百度图片的数量问题

### ISSUE THREAD

**Issue by daixiangzi** [QianyanTech/Image-Downloader#34]
1.我制定了爬取数量后，为什么只能爬取一部分，比如我制定为10000张实际只能爬2000左右，并且我修改了你代码的制定上限，我手动搜关键词也并不只有2000左右？

**Comment by aeeeeeep** [comment]
同样的问题，楼主怎么解决的？

**Comment by zhudu** [comment]
这个问题不在代码身上，是因为百度网页只提供前60页的图片信息，往后就翻不了了，所以只能爬取一千多张图片。

**Comment by lllrj** [comment]
> 

那请问有啥解决的办法吗
